ALTER TABLE ai_configurations
    ADD COLUMN IF NOT EXISTS insights_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS insights_cron VARCHAR(50) NOT NULL DEFAULT '0 0 20 * * *',
    ADD COLUMN IF NOT EXISTS evaluation_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS evaluation_sample_rate INT NOT NULL DEFAULT 1;
