-- =============================================
-- V2: Create todos table
-- =============================================
-- Each todo belongs to a user (foreign key → users.uid).
-- IDs are UUIDs generated by the backend.

CREATE TABLE todos (
    id         UUID          PRIMARY KEY DEFAULT gen_random_uuid(),
    user_uid   VARCHAR(128)  NOT NULL REFERENCES users(uid) ON DELETE CASCADE,
    text       VARCHAR(500)  NOT NULL,
    completed  BOOLEAN       NOT NULL DEFAULT FALSE,
    priority   VARCHAR(10),                        -- 'high', 'medium', 'low', or NULL
    postponed  BOOLEAN       NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Index: fast lookup of todos by user
CREATE INDEX idx_todos_user_uid ON todos(user_uid);
